common/models/File.php
<?php

declare(strict_types=1);

namespace common\models;

use common\db\ActiveQuery;

/**
 * @property int    $id
 * @property string $content_type
 * @property string $original_name
 * @property string $path
 * @property string $created_at
 *
 * @property string $thumbUrl
 * @property string $webUrl
 * @property string $realPath
 *
 * @see     File::__get
 * @property string $thumbUrl60
 * @property string $thumbUrl120
 * @property string $thumbUrl240
 * @property string $thumbUrl360
 */
class File extends \yii2kernel\models\File
{
    public static function find(): ActiveQuery
    {
        return new ActiveQuery(static::class);
    }
}

common/models/User.php
<?php

declare(strict_types=1);

namespace common\models;

use yii\db\ActiveQuery;
use yii\web\IdentityInterface;
use yii2kernel\behaviors\HashBehavior;
use yii2kernel\behaviors\TimestampBehavior;
use yii2kernel\mixin\JsonProperties;
use yii2kernel\mixin\StatusLabel;
use common\db\ActiveRecord;

/**
 * @property int    $id
 * @property int    $image_id
 * @property int    $status
 * @property string $code
 * @property string $login
 * @property string $email
 * @property array  $fields
 * @property int    $created_at
 * @property int    $updated_at
 *
 * @property File   $image
 *
 * @property string $security_password_hash
 * @property string $security_password_reset_token
 * @property string $security_auth_key
 * @property string $security_access_token
 */
class User extends ActiveRecord implements IdentityInterface
{
    use JsonProperties;
    use StatusLabel;

    public const STATUS_ACTIVE   = 'active';
    public const STATUS_INACTIVE = 'inactive';
    public const STATUS_DELETED  = 'deleted';

    /**
     * @var \common\models\User[]
     */
    private static $_user_list = [];

    public static function tableName(): string
    {
        return 'public.user';
    }

    public static function statusLabels(): array
    {
        return [
            self::STATUS_ACTIVE   => \Yii::t('app', 'Active'),
            self::STATUS_INACTIVE => \Yii::t('app', 'Inactive'),
            self::STATUS_DELETED  => \Yii::t('app', 'Deleted'),
        ];
    }

    public static function findIdentity($id)
    {
        $identity = self::findUser((int) $id);

        if ($identity !== null && $identity->status !== self::STATUS_ACTIVE) {
            return null;
        }

        return $identity;
    }

    public static function findIdentityByAccessToken($token, $type = null)
    {
        $query = self::find();

        $query->andWhere(['"user"."status"' => self::STATUS_ACTIVE]);
        $query->andWhere('"user"."fields" @> :ACCESS_TOKEN_JSON', [
            ':ACCESS_TOKEN_JSON' => json_encode(['security_access_token' => $token]),
        ]);

        /** @noinspection PhpIncompatibleReturnTypeInspection */
        return $query->one();
    }

    public static function findUser(int $id = null): ?User
    {
        if (empty($id)) {
            return null;
        }

        if (array_key_exists($id, self::$_user_list) === false) {
            $isCurrent = isset(\Yii::$user->id) && $id === \Yii::$user->id;

            self::$_user_list[$id] = $isCurrent ? \Yii::$user : static::find()->andWhere(['id' => $id])->one();
        }

        return self::$_user_list[$id];
    }

    public static function jsonProperties(): array
    {
        return [
            'security_auth_key',
            'security_password_hash',
            'security_password_reset_token',
            'security_access_token',
        ];
    }

    public static function labels(): array
    {
        return [
            'id'                            => \Yii::t('app', 'ID'),
            'image'                         => \Yii::t('app', 'Image'),
            'image_id'                      => \Yii::t('app', 'Image'),
            'status'                        => \Yii::t('app', 'Status'),
            'name'                          => \Yii::t('app', 'Name'),
            'login'                         => \Yii::t('app', 'Login'),
            'email'                         => \Yii::t('app', 'E-mail'),
            'security_auth_key'             => \Yii::t('app', 'Authorization key'),
            'security_password_hash'        => \Yii::t('app', 'Password hash'),
            'security_password_reset_token' => \Yii::t('app', 'Password reset token'),
            'security_access_token'         => \Yii::t('app', 'Access token'),
            'created_at'                    => \Yii::t('app', 'Created at'),
            'updated_at'                    => \Yii::t('app', 'Updated at'),
        ];
    }

    public function getId()
    {
        return $this->getPrimaryKey();
    }

    public function getAuthKey(): string
    {
        return $this->security_auth_key;
    }

    public function validateAuthKey($authKey): bool
    {
        return $this->getAuthKey() === $authKey;
    }

    public function behaviors(): array
    {
        return [
            TimestampBehavior::class,
            [
                'class'     => HashBehavior::class,
                'length'    => 12,
                'attribute' => 'code',
            ],
        ];
    }

    public function rules(): array
    {
        $statusLabels = self::statusLabels();

        return [
            [['status', 'email'], 'required'],
            [['image_id'], 'integer'],
            [
                ['image_id'],
                'exist',
                'skipOnError'     => true,
                'targetClass'     => File::class,
                'targetAttribute' => ['image_id' => 'id'],
            ],
            [['status'], 'in', 'range' => \array_keys($statusLabels)],
            [['email'], 'email'],
            [['login', 'email'], 'unique'],
        ];
    }

    public function fields()
    {
        return [
            'id',
            'image' => function (User $user) {
                return $user->image ? $user->image->getWebUrl(true) : null;
            },
            'status',
            'code',
            'login',
            'email',
            'created_at',
            'updated_at',
        ];
    }

    public function getImage(): ActiveQuery
    {
        return $this->hasOne(File::class, ['id' => 'image_id'])->andWhere(['content_type' => File::$imageMimeTypes]);
    }
}

frontend/controllers/AuthController.php
<?php

declare(strict_types=1);

namespace frontend\controllers;

use common\models\User;
use common\web\Controller;
use frontend\forms\SignIn;
use frontend\forms\SignUp;

class AuthController extends Controller
{
    /**
     * Logs in a user.
     *
     * @return mixed
     * @throws \yii\base\InvalidParamException
     */
    public function actionSignIn()
    {
        $formModel = new SignIn();

        if ($formModel->load(\Yii::$app->getRequest()->post())) {
            if ($formModel->save()) {
                return $this->redirect(['/cabinet/default/index']);
            }
        }

        return $this->render('sign-in', [
            'formModel' => $formModel,
        ]);
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionSignOut()
    {
        \Yii::$app->user->logout();

        return $this->redirect(['/site/index']);
    }

    /**
     * Signs user up.
     *
     * @return mixed
     * @throws \yii\db\Exception
     * @throws \yii\base\Exception
     * @throws \yii\base\InvalidParamException
     */
    public function actionSignUp()
    {
        $model     = new User();
        $formModel = new SignUp($model);

        if ($formModel->load(\Yii::$app->getRequest()->post())) {
            if ($formModel->save() && \Yii::$app->getUser()->login($model)) {
                return $this->redirect(['/site/index']);
            }
        }

        return $this->render('sign-up', [
            'formModel' => $formModel,
        ]);
    }
}

frontend/controllers/SiteController.php
<?php

declare(strict_types=1);

namespace frontend\controllers;

use yii\web\ErrorAction;
use common\web\Controller;

class SiteController extends Controller
{
    public function actions(): array
    {
        return [
            'error' => [
                'class' => ErrorAction::class,
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index');
    }
}

frontend/views/layouts/main.php
<?php

/**
 * @var \common\web\View $this
 * @var string           $content
 */

declare(strict_types=1);

use yii\helpers\Html;
use frontend\assets\LayoutAsset;

LayoutAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= \Yii::$app->language ?>">
<head>
    <meta charset="<?= \Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title ? : \Yii::$app->name); ?></title>
    <?php $this->head(); ?>
</head>
<body>
<?php $this->beginBody(); ?>

<header>
    <?= $this->render('partial/navigation'); ?>
</header>

<div class="page-wrapper">
    <div class="container">
        <?= $content; ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p>&copy; <?= Html::a(Yii::$app->name, ['/site/index']); ?> <?= date('Y'); ?></p>
    </div>
</footer>

<?php $this->endBody(); ?>
</body>
</html>
<?php $this->endPage(); ?>

frontend/views/layouts/partial/navigation.php
<?php

/**
 * @var \common\web\View $this
 */

declare(strict_types=1);

$menu = [
    [
        'label' => Yii::t('app', 'Sign in'),
        'url'   => ['/auth/sign-in'],
    ],
    [
        'label' => Yii::t('app', 'Sign up'),
        'url'   => ['/auth/sign-up'],
    ],
];

if (Yii::$app->getUser()->getIsGuest() === false) {
    $menu = [
        [
            'label' => Yii::t('app', 'Cabinet'),
            'url'   => ['/cabinet/default/index'],
        ],
        [
            'label' => Yii::t('app', 'Sign out'),
            'url'   => ['/auth/sign-out'],
        ],
    ];
}
?>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <?= \yii\helpers\Html::a('<img src="/img/logo.png">', ['/site/index'], [
            'class' => 'navbar-brand',
        ]); ?>

        <button class="navbar-toggler"
                type="button"
                data-toggle="collapse"
                data-target="#header-navbar"
                aria-controls="header-navbar"
                aria-expanded="false"
                aria-label="<?= Yii::t('app', 'Toggle navigation'); ?>">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="header-navbar">
            <?= \yii\widgets\Menu::widget([
                'items'        => $menu,
                'itemOptions'  => [
                    'class' => 'nav-item',
                ],
                'linkTemplate' => '<a href="{url}" class="nav-link">{label}</a>',
                'options'      => [
                    'class' => 'navbar-nav ml-auto',
                ],
            ]); ?>
        </div>
    </div>
</nav>

frontend/views/site/error.php
<?php

/**
 * @var \common\web\View $this
 * @var string           $name
 * @var string           $message
 * @var \Exception       $exception
 */

declare(strict_types=1);

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>
</div>

frontend/views/site/index.php
<?php

/**
 * @var \common\web\View $this
 */

declare(strict_types=1);

?>

<section class="section-site-index"></section>